### Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .simple_fcb1010 import simple_fcb1010

def create_instance(c_instance):
    if c_instance is None:
        print("Error: Ableton passed None for c_instance")
    return simple_fcb1010(c_instance)
